# Generated by Django 2.1.2 on 2019-06-23 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments_text', models.TextField(verbose_name='Текст комментария')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
